import { supabase } from "@/integrations/supabase/client";

export interface AdminAppointment {
  id: string;
  confirmation_number: string;
  customer_id: string | null;
  guest_name: string | null;
  guest_email: string | null;
  guest_phone: string | null;
  barber_id: string | null;
  service_id: string;
  appointment_date: string;
  appointment_time: string;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
  payment_status: 'none' | 'deposit_paid' | 'fully_paid';
  payment_amount: number | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
  barbers?: { full_name: string } | null;
  services?: { name: string; regular_price: number } | null;
  customer_name?: string | null;
}

// Get all appointments with related data
export const getAllAppointments = async (): Promise<AdminAppointment[]> => {
  const { data, error } = await supabase
    .from('appointments')
    .select(`
      *,
      barbers(full_name),
      services(name, regular_price)
    `)
    .order('appointment_date', { ascending: false })
    .order('appointment_time', { ascending: false });

  if (error) throw error;
  
  // Fetch customer names for registered users
  const appointmentsWithCustomers = await Promise.all(
    (data || []).map(async (apt: any) => {
      if (apt.customer_id) {
        const { data: profile } = await supabase
          .from('profiles')
          .select('full_name')
          .eq('id', apt.customer_id)
          .maybeSingle();
        
        return {
          ...apt,
          customer_name: profile?.full_name || null,
        };
      }
      return { ...apt, customer_name: null };
    })
  );
  
  return appointmentsWithCustomers as AdminAppointment[];
};

// Create appointment manually (admin only)
export const createManualAppointment = async (appointmentData: {
  customer_id: string | null;
  guest_name?: string;
  guest_email?: string;
  guest_phone?: string;
  barber_id: string;
  service_id: string;
  appointment_date: string;
  appointment_time: string;
  notes?: string;
  payment_amount?: number;
  payment_status?: 'none' | 'deposit_paid' | 'fully_paid';
  status?: 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
}) => {
  // confirmation_number is auto-generated by database trigger
  const { data, error } = await supabase
    .from('appointments')
    .insert([appointmentData as any])
    .select()
    .single();

  if (error) throw error;
  return data;
};

// Update appointment status
export const updateAppointmentStatus = async (
  id: string,
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'no_show'
) => {
  const { error } = await supabase
    .from('appointments')
    .update({ status })
    .eq('id', id);

  if (error) throw error;
};

// Update appointment payment status
export const updatePaymentStatus = async (
  id: string,
  payment_status: 'none' | 'deposit_paid' | 'fully_paid'
) => {
  const { error } = await supabase
    .from('appointments')
    .update({ payment_status })
    .eq('id', id);

  if (error) throw error;
};

// Get all customers (profiles)
export const getAllCustomers = async () => {
  const { data, error } = await supabase
    .from('profiles')
    .select('*')
    .order('full_name', { ascending: true });

  if (error) throw error;
  return data || [];
};

// Get available time slots for a barber on a specific date
export const getAvailableTimeSlots = async (
  barberId: string,
  date: string,
  serviceDuration: number
): Promise<string[]> => {
  // Get barber's availability for the day of week
  const dayOfWeek = new Date(date).getDay();
  
  const { data: availability, error: availError } = await supabase
    .from('barber_availability')
    .select('*')
    .eq('barber_id', barberId)
    .eq('day_of_week', dayOfWeek)
    .eq('is_available', true)
    .single();

  if (availError || !availability) return [];

  // Get existing appointments for that barber on that date
  const { data: appointments, error: apptError } = await supabase
    .from('appointments')
    .select('appointment_time, services(duration_minutes)')
    .eq('barber_id', barberId)
    .eq('appointment_date', date)
    .neq('status', 'cancelled');

  if (apptError) return [];

  // Generate time slots
  const slots: string[] = [];
  const startTime = new Date(`2000-01-01T${availability.start_time}`);
  const endTime = new Date(`2000-01-01T${availability.end_time}`);
  
  let currentTime = startTime;
  while (currentTime < endTime) {
    const timeString = currentTime.toTimeString().slice(0, 5);
    
    // Check if slot is available (not overlapping with existing appointments)
    const isAvailable = !appointments?.some((apt: any) => {
      const aptTime = new Date(`2000-01-01T${apt.appointment_time}`);
      const aptDuration = apt.services?.duration_minutes || 30;
      const aptEnd = new Date(aptTime.getTime() + aptDuration * 60000);
      
      const slotTime = new Date(`2000-01-01T${timeString}`);
      const slotEnd = new Date(slotTime.getTime() + serviceDuration * 60000);
      
      // Check for overlap
      return slotTime < aptEnd && slotEnd > aptTime;
    });
    
    if (isAvailable) {
      slots.push(timeString);
    }
    
    // Move to next slot (30-minute intervals)
    currentTime = new Date(currentTime.getTime() + 30 * 60000);
  }
  
  return slots;
};
